language: php

php:
  - 7.1
  - 7.2

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction
  - export LANG=C
  - export PATH=vendor/bin:$PATH

script:
  # start a web server on port 8080, running in the background
  - bin/console server:start
  - vendor/bin/behat -fprogress --strict --lang=en

after_failure:
  - cat server.log
  - sudo cat /var/log/nginx/error.log
  - sudo cat /var/log/nginx/access.log
