language: php

php:
  - 7.2
  - hhvm

before_install:
  # start a web server on port 8080, running in the background
  - bin/start_server.sh

before_script:
  - composer self-update
  - composer install --prefer-source
  - export LANG=C
  - export PATH=vendor/bin:$PATH

script:
  - behat -fprogress --strict

after_failure:
  - cat server.log
  - sudo cat /var/log/nginx/error.log
  - sudo cat /var/log/nginx/access.log

matrix:
  allow_failures:
    - php: hhvm
